services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: refund_sentinel_backend

    restart: unless-stopped

    environment:
      DATABASE_URL: postgresql+psycopg://sentinel:sentinel_dev_password@db:5432/refund_sentinel
      APP_ENV: development
      APP_API_KEY: replace_with_a_random_string_for_local_dev

      ML_MODEL_PATH: "/app/backend/app/models/model.json"

    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy


  db:
    image: postgres:16-alpine
    container_name: refund_sentinel_db
    restart: unless-stopped

    environment:
      POSTGRES_DB: refund_sentinel
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel_dev_password

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sentinel -d refund_sentinel"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


volumes:
  postgres_data:
    driver: local